apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.frontend.port }}
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: 9113