prometheus:
  server:
    extraScrapeConfigs: |
      - job_name: 'nginx'
        metrics_path: /nginx_metrics
        static_configs:
          - targets: ['yarin.services.svc.cluster.local:80']
            labels:
              instance: nginx-frontend

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: false
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000