prometheus:
  server:
    extraScrapeConfigs: |
      - job_name: 'nginx'
        static_configs:
          - targets: ['frontend:80/nginx_metrics']
            labels:
              instance: nginx-frontend
grafana:
  adminPassword: prom-operator
  ingress:
    enabled: false
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000