prometheus:
    extraScrapeConfigs: |
      - job_name: nginx
        metrics_path: /metrics
        static_configs:
          - targets:
              - frontend.services.svc.cluster.local:9113

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: false
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000