apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.appNamespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontendIngress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontendIngress.serviceName }}
            port:
              number: {{ .Values.frontendIngress.servicePort }}
